# Generated by Django 4.1.5 on 2023-01-24 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster', models.ImageField(upload_to='poster_images/')),
                ('artist_name', models.CharField(max_length=100)),
                ('total_registrations', models.IntegerField(default=0)),
                ('release_date', models.DateTimeField(verbose_name='release date')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='publish date')),
                ('image_url', models.CharField(max_length=64, null=True)),
                ('genres', models.CharField(max_length=200, null=True)),
                ('lyrics', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registrated', models.DateField(default=django.utils.timezone.now)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concert.concert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='songs',
            field=models.ManyToManyField(to='concert.song'),
        ),
    ]
