# Generated by Django 4.1.5 on 2023-01-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
